### PR TITLE
All unable to load notifications (All Domains, All Vulnerabilities, Organizations, Users)-CRASM-493

### LINKED ISSUE #490: Remove all "Unable to Load" notifications CRASM-493
# 🐛 Summary #

- The "Unable to Load" notification is displayed when loading "All Domains" and "All Vulnerabilities" data list, even if the screens are successfully loaded. This notification should be applicable only when there is an unsuccessful load. 

## To reproduce ##

- Implement conditional rendering based on state variable.
- Loading will be set to true or false if fetched data is displayed or not displayed respectively
- Provide an option for users to retry loading data with appropriate feedback.

## Expected behavior ##

- Once implemented correctly, the "unable to load" waring would be replaced by a circular spinner loading indicator, while the initial functionality in the background

### PR DESCRIPTION
**Pull request by lwersiy**
## 🗣 Description ##
When users click to load list (All Domains, All Vulnerabilities, Organizations, Users), "Unable to Load" notification is displayed even with a successful load. This notification was replaced with a more user friendly message, and a retry will be prompted in case of an error loading.

## 💭 Motivation and context ##

- Implement conditional rendering based on state variable.
- Loading set to true or false if fetched data is displayed or not displayed respectively
- Provided an option for users to retry loading data with appropriate feedback.

closes #490 
closes CRASM-493

## 🧪 Testing ##

Local

## ALL DOMAINS ##
loading domains
error loading domains

## ORGANIZATION ##
loading orgs
erro loading org

## USERS ##
loading users
error loading users

## ALL VULNERABILITIES ##
loading vulns
error loading vulns

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by ameliav — CHANGES_REQUESTED** [review]
If you are going to have a “Retry” button, make sure you also reset the state of loadingError and isLoading inside your reset function.

**Comment by hawkishpolicy** [comment]
> If you are going to have a “Retry” button, make sure you also reset the state of loadingError and isLoading inside your reset function.

Great catch! Thanks.

**Review by ameliav — CHANGES_REQUESTED** [review]
Since you've added a loadingError state to the vulnerabilities table, you should add setLoadingError(true); to line 157 in Vulnerabilities.tsx so that your alert will show rather than an empty table when there is an error loading the table.

Current
image

When fixed
image

**Review by ameliav — APPROVED** [review]
LGTM!

**Review by Matthew-Grayson — APPROVED** [review]
I'm not a huge fan of how dire the error message looks with the double exclamation point. Even so, looks great!!

**Comment by hawkishpolicy** [comment]
We can change it. Single exclamation point?

Thomas Johnson
Junior Developer, ASM
Cybersecurity and Infrastructure Security Agency
M: 202-394-5991 | ***@***.***


From: Matthew ***@***.***>
Date: Monday, August 5, 2024 at 9:44 AM
To: cisagov/XFD ***@***.***>
Cc: JOHNSON, THOMAS J (CTR) ***@***.***>, Comment ***@***.***>
Subject: Re: [cisagov/XFD] All unable to load notifications (All Domains, All Vulnerabilities, Organizations, Users)-CRASM-493 (PR #504)
CAUTION: This email originated from outside of DHS. DO NOT click links or open attachments unless you recognize and/or trust the sender. Contact your component SOC with questions or concerns.


@Matthew-Grayson approved this pull request.

I'm not a huge fan of how dire the error message looks with the double exclamation point. Even so, looks great!!

**Comment by lwersiy** [comment]
Exclamation changes pushed up

**Review by schmelz21 — APPROVED** [review]

**Pull request merged**
