### PR TITLE
Fixed UserForm.tsx to recognize hyphenated and apostrophe First and L…

### LINKED ISSUE #585: Hyphenated Names not Recognized (CRASM-619)
# 🐛 Summary #

In the First Name and Last Name text field, hyphenated and apostrophe names are not recognized.

## Expected behavior ##

Users should be able to update/edit without getting any error message.

## Any helpful log output or screenshots ##

Screenshot 2024-09-04 at 11 06 20 AM

Screenshot 2024-09-04 at 12 30 17 PM

### PR DESCRIPTION
**Pull request by lwersiy**
## 🗣 Description ##

- This PR fixes the error messages when editing/updating user and recognizes hyphenated and apostrophe names such abc-xyz, A'bcd

## 💭 Motivation and context ##

- Fixed UserForm.tsx to recognize hyphenated and apostrophe First and Last names when editing or updating users by including - and ' to the logic. 

Closes #585 
Resolves CRASM-619

## 🧪 Testing ##

Tested Locally

## 📷 Screenshots (if appropriate) ##

Before Implementation
Screenshot 2024-09-04 at 11 06 20 AM
Screenshot 2024-09-04 at 12 30 17 PM

After implementation
Screenshot 2024-09-04 at 12 48 34 PM
Screenshot 2024-09-04 at 12 49 08 PM

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by schmelz21 — APPROVED** [review]
LGTM. Signed off by Step-hen Schmelz

**Review by chrtorres — APPROVED** [review]
LGTM

**Review by nickviola — APPROVED** [review]
LGTM

**Review by hawkishpolicy — APPROVED** [review]
Tested locally with hyphens and apostrophes. LGTM.

**Pull request merged**
