### PR TITLE
Filter Resources on RSC Dashboard Details Page

### LINKED ISSUE #182: Filter Displayed RSC Resources by User Response
# 💡 Summary #

Need to filter the resources displayed on the ReadySetCyber (RSC) Dashboard detailed view. 

## Motivation and context ##

Currently, all resources are displayed regardless of a user's response. Users should only be able to view a resource if they have responded "No", "Not in Scope" , or "Not Started".

## Acceptance criteria ##

- [ ] Resources displayed on users "No", "Not in Scope" or "Not Started" response.
- [ ] Appropriate Resources are displayed.

### PR DESCRIPTION
**Pull request by chrtorres**
#  #

## 🗣 Description ##

- Created helper functions to filter resources according to a RSC user's response.
- Created component to display icons related to a users associated resource type.
- Fixed styling errors on response display.

## 💭 Motivation and context ##

Closes issue #182 

## 📷 Screenshots (if appropriate) ##
Resource displayed if user answers "No", "Not in Scope", or "Not Started":
image

Otherwise, no resource is displayed
image

## ✅ Pre-approval checklist ##

- [x] Resources displayed on users "No", "Not in Scope" or "Not Started" response.
- [x] Appropriate Resources are displayed.
- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by ameliav — APPROVED** [review]
LGTM

**Comment by ameliav** [comment]
I like the use of screenshots. I suggest @chrtorres and @hawkishpolicy add screenshots to all PRs with UI changes moving forward for ease of context.

**Comment by hawkishpolicy** [comment]
Will do.

**Review by schmelz21 — APPROVED** [review]
Approved.

**Pull request merged**
