### PR TITLE
261 UI: Update All Domains & All Vulnerabilities Tables

### LINKED ISSUE #261: UI: Update All Domains/All Vulnerabilities Tables
# 💡 Summary #
What is the work, as a high-level summary?

Provide an update to the All Domains and All Vulnerabilities tables in the Inventory section.
- Update the styling and layout to match that of the Organizations table.
- Update the filtering.
- Update pagination.

## Motivation and context ##
Why does this work belong in this project?

- Improved user experience
- Updated design
- UI consistency

## Implementation notes ##

Existing Design:
Screenshot 2024-05-16 at 3 45 06 PM
Screenshot 2024-05-16 at 3 45 11 PM

Proposed Design:
Screenshot 2024-05-16 at 3 45 21 PM

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

### PR DESCRIPTION
**Pull request by hawkishpolicy**
#  #
Replace old React Table based tables with the new MUI Data Grid X tables
## 🗣 Description ##
 - Copied functionality of old Domains and Vulnerabilities tables into the more modern MUI Data Grid X components.
 - Removed unused code.
 - Kept server side pagination and filtering.
 - Sorting is handled by new component out of the box.

## 💭 Motivation and context ##
- Brings Domains and Vulnerabilities tables inline with new Organizations table.
- Updates style.
- Improves UX.
- Closes #261 

## 📷 Screenshots (if appropriate) ##

Uncomment this section if a screenshot is needed.

Screenshot 2024-05-24 at 1 14 54 PM
Screenshot 2024-05-24 at 1 15 00 PM
Screenshot 2024-05-24 at 1 14 36 PM
Screenshot 2024-05-24 at 1 14 27 PM

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by chrtorres — APPROVED** [review]
This looks great. Maybe changing 'testDomain' to something more recognizable would be best. Otherwise LGTM.

**Review by schmelz21 — CHANGES_REQUESTED** [review]
This is looking great. So far the only thing I see is on the assets details page has a button that shouldn't be there. Looks like carried over from the templated frame.

Screenshot 2024-06-06 at 2 49 59 PM

**Comment by hawkishpolicy** [comment]
I was under the impression that button took you to the domain in question.

**Comment by schmelz21** [comment]
> I was under the impression that button took you to the domain in question.

@hawkishpolicy - after our review, yes let's keep it in this code push as it is exsiting functionality. We can make an Issue to review at a later time. Thanks. Approving this PR.

**Review by schmelz21 — APPROVED** [review]
After UAT and Review - LGTM

**Review by rapidray12 — APPROVED** [review]
Change testdomain to domain

**Review by cduhn17 — APPROVED** [review]
LGTM

**Pull request merged**
