### PR TITLE
Maintains filter counts and order after applying a filter

### PR DESCRIPTION
**Pull request by jayjaybunce**
#  #

## 🗣 Description ##

- Updated FaceFilter component to memoize options
- Prevents the filter counts associated with each filter from rerendering per [CRASM-329](https://maestro.dhs.gov/jira/browse/CRASM-329)

## 💭 Motivation and context ##

Resolves [CRASM-329](https://maestro.dhs.gov/jira/browse/CRASM-329)

## 🧪 Testing ##

After making the mentioned changes, I tested each filter that uses the FaceFilter component to ensure the filters are correctly applied and results return are appropriate to the filters used

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by rapidray12 — APPROVED** [review]
Good to go

**Review by Matthew-Grayson — APPROVED** [review]
Looks great

**Review by nickviola — APPROVED** [review]
LGTM

**Review by hawkishpolicy — APPROVED** [review]
lgtm.

**Pull request merged**
