### PR TITLE
Convert Pie Charts to Bar Charts

### PR DESCRIPTION
**Pull request by nickviola**
Convert Pie Charts to Bar Graphs

#  #

## 🗣 Description ##
Resolves CRASM-411: https://maestro.dhs.gov/jira/browse/CRASM-411

- Converts Pie chart component to Bar charts per leadership request. 
- Adds Aria lables for bar charts
- Make bar chart items supoort keyboard tab commands for navigation
- Make bar chart item clickable to display relevant results
- Import color scheme from utils for each Bar chart items
- Renamed Component to reflect BarChart vs. PieChart and updated imports

## 💭 Motivation and context ##
Pie charts were not meeting 508 requirements so per CRASM-411, we decided to convert pie charts to bar charts.

## 🧪 Testing ##
Confirm that bar charts render on landing page instead of pie charts. Also confirm that the charts respond to tab keyboard navigation. Confirm aria labels.

## ✅ Pre-approval checklist ##
Screenshot 2024-07-15 at 4 32 13 PM
Screenshot 2024-07-15 at 4 32 04 PM

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by rapidray12 — COMMENTED** [review]
Update the hard coded colors and remove the patterns

**Review by ameliav — APPROVED** [review]
LGTM

**Comment by nickviola** [comment]
> 542216d

Resolved in commit: [542216d](https://github.com/cisagov/XFD/pull/448/commits/542216d674f2877669952a267df17717d2dfc01c)

**Review by hawkishpolicy — COMMENTED** [review]
Tooltips don't seem to be working.

**Review by schmelz21 — APPROVED** [review]
LGTM.

@rapidray12 , @hawkishpolicy - you all want to take another look?

**Comment by nickviola** [comment]
> Tooltips don't seem to be working.

I'm not seeing any tooltips working after merging the latest develop. I've added a TODO to determine if we want to keep tooltips or create an issue to fix them globally.

**Review by cduhn17 — APPROVED** [review]
LGTM

**Comment by schmelz21** [comment]
@rapidray12 , @hawkishpolicy  - you satisfied with this PR?

**Comment by hawkishpolicy** [comment]
> @rapidray12 , @hawkishpolicy - you satisfied with this PR?

Yep. Creating an issue works for me.

**Review by hawkishpolicy — APPROVED** [review]
LGTM.

**Pull request merged**
