### PR TITLE
Allows regional admin to delete user via User Registration UI.

### PR DESCRIPTION
**Pull request by jayjaybunce**
## 🗣 Description ##

Updates delete user handler to enable regional admins to perform this action that's available in the UI. 

## 💭 Motivation and context ##

Resolves: https://maestro.dhs.gov/jira/browse/CRASM-320

## 🧪 Testing ##

Case 1. User with globalAdmin is able to deny a pending request in the User Registration UI
Cast 2. User with regionalAdmin is able to deny a pending request in the User Registration UI

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by schmelz21 — APPROVED** [review]

**Review by cduhn17 — APPROVED** [review]
LGTM

**Review by nickviola — CHANGES_REQUESTED** [review]
Looks like there is a minor linter issue to insert a newline: https://github.com/cisagov/XFD/pull/345/files#:~:text=api/users.ts-,GitHub,-Actions.

 Aside from that it LGTM.

**Comment by jayjaybunce** [comment]
> Looks like there is a minor linter issue to insert a newline: https://github.com/cisagov/XFD/pull/345/files#:~:text=api/users.ts-,GitHub,-Actions.
> 
> Aside from that it LGTM.

Lint issue resolved

**Comment by schmelz21** [comment]
> Looks like there is a minor linter issue to insert a newline: https://github.com/cisagov/XFD/pull/345/files#:~:text=api/users.ts-,GitHub,-Actions.
> 
> Aside from that it LGTM.

@nickviola - can you re-review the linting update?

**Review by Matthew-Grayson — APPROVED** [review]
Good to merge.
As a todo, I suggest we only allow regional admins to delete users from the same region.

**Review by nickviola — APPROVED** [review]
LGTM

**Pull request merged**
