### PR TITLE
Fix docker-compose - Depecrated

### PR DESCRIPTION
**Pull request by aloftus23**
#  #

## 🗣 Description ##

GitHub deprecated v1 of Docker compose which used the docker-compose command. The updated version uses "docker compose" instead.

Updated all uses in github actions and the npm aliases.

Reference:
https://github.com/orgs/community/discussions/116610

## 💭 Motivation and context ##

Docker-compose command is breaking in github actions.

## 🧪 Testing ##

Tested full build locally and passes pre-commits and github checks.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Revert dependencies to default branches.
- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Review by nickviola — APPROVED** [review]
LGTM

**Review by cduhn17 — APPROVED** [review]
LGTM

**Review by Matthew-Grayson — APPROVED** [review]

**Review by schmelz21 — APPROVED** [review]

**Comment by schmelz21** [comment]
@dav3r  or @jsf9k - Looks like we need your approval on this one. Thanks

**Review by dav3r — APPROVED** [review]
Looks fine to me, though I encourage you to follow our convention of using the long names of command flags (e.g. `docker compose up --detach` instead of `docker compose up -d`) whenever possible.  It makes the code more readable.

**Pull request merged**
