### PR TITLE
Update Alert icon parameters for 508 compliance in Notifications.tsx

### PR DESCRIPTION
**Pull request by ameliav**
#  #

## 🗣 Description ##
The Icons in the Admin Tools Notifications page are missing alternative text. Provide concise and meaningful text alternates for all non-text content. The description needs to provide enough information so that the purpose of non-text content can be understood even if it is removed.

## 💭 Motivation and context ##
The aria-label should be updated and the following fix needs to be made.
1 - Remove aria-hidden="true"
2 - Add role="img"
3 - Update the aria-label="Information Alert"
JIRA CRASM-521

## 🧪 Testing ##
Go to the notifications page and check that the icons in the alerts in the console no longer has aria-hidden as true, there is a role tag set to img, and aria label now says Information Alert.

## 📷 Screenshots (if appropriate) ##

Original

image-2024-07-24-15-44-13-756

Updated

image

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by Matthew-Grayson — APPROVED** [review]
🚀

**Review by chrtorres — APPROVED** [review]
Simple enough, LGTM

**Review by hawkishpolicy — APPROVED** [review]
LGTM.

**Review by nickviola — APPROVED** [review]
LGTM

**Pull request merged**
