### PR TITLE
Add tooltip to Severity Levels bar graph in Overview (CRASM-526)

### LINKED ISSUE #503: Add tooltip to Severity Levels bar graph in Overview (CRASM-526)
# 🐛 Summary #
- All other graphs and info cards have functioning tool tips with exception to Severity Levels.
- This needs to be addressed.

## To reproduce ##

1. Hover over bar layer.

## Expected behavior ##

1. A tooltip tip to appear.

### PR DESCRIPTION
**Pull request by hawkishpolicy**
#  #
- Added tooltip to Severity Levels bar graph on Overview page.
## 🗣 Description ##
- Wrapped Custom Bar Layer in MUI tooltip.
- Made graph focusable.
- Edited verbiage of tooltip for clarity.
- Edited aria-labels for clarity.

## 💭 Motivation and context ##
- Closes #503 
- Closes CRASM-526

## 📷 Screenshots (if appropriate) ##

Screenshot 2024-08-01 at 1 25 14 PM

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by chrtorres — APPROVED** [review]
Maybe some screenshots, but otherwise LGTM

**Review by ameliav — COMMENTED** [review]
Was adding the word "test" to line 120 intentional?

**Comment by hawkishpolicy** [comment]
> Was adding the word "test" to line 120 intentional?

Nope. I have no idea where that came from. Let me remove it.

**Review by ameliav — APPROVED** [review]
LGTM

**Review by schmelz21 — APPROVED** [review]

**Pull request merged**
