### PR TITLE
Removed unused CSS from Users (CRASM-510)

### LINKED ISSUE #477: Remove legacy unused CSS from Users (CRASM-510)
# 🐛 Summary #

- The refactoring of the Users table in MUI left a bunch of unused CSS.
- This needs to be reviewed and deleted.

### PR DESCRIPTION
**Pull request by hawkishpolicy**
- The recent refactor of the Users table in MUI makes pre-existing CSS unnecessary.
#  #

## 🗣 Description ##
- Deleted Users.module.scss
- Removed import of Users.module.scss from Users.tsx
- Deleted unused CSS classes from Users.tsx
- Added Box and Stack elements to Users.tsx for uniformity.
- Changed width to 70% to match other pages and match previous design.

## 💭 Motivation and context ##
- Cleans up code base, reduces footprint, and simplifies project.
- Closes #477 
- Closes CRASM-510

## 📷 Screenshots (if appropriate) ##
Screenshot 2024-07-24 at 4 06 08 PM
Screenshot 2024-07-24 at 4 06 35 PM

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by chrtorres — APPROVED** [review]
LGTM

**Review by ameliav — COMMENTED** [review]
Do you have a before and after screenshot as an example of the change?

**Comment by hawkishpolicy** [comment]
I can add them

**Comment by hawkishpolicy** [comment]
I'll add them for all the CSS focused PRs.

**Review by ameliav — APPROVED** [review]
LGTM!

**Review by schmelz21 — APPROVED** [review]

**Pull request merged**
