### PR TITLE
439 UI moved search from header to inventory filter CRASM-408

### LINKED ISSUE #439: UI: Move Search from Header to Inventory Filter (CRASM-408)
# 💡 Summary #

To move the Search from Header to Inventory, above filter

## Motivation and context ##

- Once a search is entered in the searchbar, it automatically redirect user to the inventory search results, it is therefore not required to have the searchbar location on the header.
- This isn't a global search, it will be more applicable if the searchbar is removed from the header into inventory, above the filter.

- From (CRASM-408)

## Implementation notes ##

- Import the necessary modules, components, and packages to FilterDrawer, then relocate the code from component/header to search/FilterDrawer, integrate the searchbar components in the inventory page, resize to fit.

Screenshot 2024-07-12 at 11 20 37 AM

- what this would look like
- how this would act
- any related work, including links to related issues

Screenshot 2024-07-16 at 5 59 43 PM

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

### PR DESCRIPTION
**Pull request by lwersiy**
## 🗣 Description ##

- Imported the necessary modules, and components to FilterDrawer.tsx
- Relocated the searchBar block from component/header.tsx to search/FilterDrawer.tsx
- Integrated the searchBar components in the inventory page
- Provided border and keyboard visible indicator to  searchBar

## 💭 Motivation and context ##

The search isn't a global search therefore it removes the searchBar component from the global to the inventory page. 
closes #439 
closes CRASM-408 

## 🧪 Testing ##
Local

## 📷 Screenshots (if appropriate) ##

Screenshot 2024-07-12 at 11 20 37 AM

Screenshot 2024-07-16 at 5 59 43 PM

Screenshot 2024-07-17 at 11 52 15 AM

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by nickviola — APPROVED** [review]
LGTM

**Review by schmelz21 — CHANGES_REQUESTED** [review]
@lwersiy - I am not getting any results when I run a search. Also on my local machine, the footer is bouncing up to the middle of the page. Can you take a look.
Screenshot 2024-07-17 at 4 53 24 PM

**Comment by lwersiy** [comment]
Yes the footer does move, I'll take a look

**Comment by hawkishpolicy** [comment]
Weird. I'll give it a look too.

**Comment by lwersiy** [comment]
I've got the footer stabled, I'm not sure why Stephen doesn't get results when he runs search. 
anyone having that same problem?

**Comment by schmelz21** [comment]
> I've got the footer stabled, I'm not sure why Stephen doesn't get results when he runs search. anyone having that same problem?

I will retest

**Comment by schmelz21** [comment]
> I've got the footer stabled, I'm not sure why Stephen doesn't get results when he runs search. anyone having that same problem?

@lwersiy - It looks like the footer issue is greater in scope than just the Inventory page. We will be recording it as a bug, and we can consider that it is out of scope for this ticket. Looking to get one more review with successful search, as my issue may be associated to my dev envirionment. Upon confirmation, we can merge the update.

**Review by chrtorres — APPROVED** [review]
Introduces bug with "Save Search" but may be out of scope. Searching returns results and functions as expected.
Screenshot 2024-07-18 at 4 40 00 PM

**Review by ameliav — CHANGES_REQUESTED** [review]
Please update the branch to add the latest from develop.

Also there is a linter error.
image

**Review by ameliav — APPROVED** [review]
Works for me now!

**Review by schmelz21 — APPROVED** [review]

**Comment by schmelz21** [comment]
LGTM - thanks all with effort on this review. 
@chrtorres - Creating bug ticket for Save Search Issue.

**Pull request merged**
