### PR TITLE
Excludes dhs region organization selections

### PR DESCRIPTION
**Pull request by jayjaybunce**
#  #

## 🗣 Description ##

- Filters any `dhs region` organizations out of the organization search and selection as well as from the initial filters we populate on page load.
- This provides a better first view for these users as they will be presented with their region 3 data rather than an empty dashboard

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by cduhn17 — APPROVED** [review]
LGTM

**Review by cduhn17 — APPROVED** [review]
LGTM

**Review by ameliav — APPROVED** [review]
Working for me. I assigned myself to an organization called DHS Region 3 and I couldn't find it in the organization search.

image

**Review by hawkishpolicy — COMMENTED** [review]
How important is the "c" missing in exclude in refinedOrgs at Line 102?

**Review by hawkishpolicy — APPROVED** [review]
I replicated what Amelia did:
- Added an org named dhs region 3 and it does not show up.
- Commented out the new exclusion and it does show up.

LGTM.

**Review by chrtorres — APPROVED** [review]

**Review by ameliav — CHANGES_REQUESTED** [review]
Actually, I found an issue.

The domains and vulnerabilities table is now showing no entries if your default org is "DHS Region x"

image
image

**Review by ameliav — APPROVED** [review]
LGTM 👍

**Pull request merged**
