### PR TITLE
Add fixes for minio and redirect s3 client to minio for local dev

### PR DESCRIPTION
**Pull request by nickviola**
#  #

## 🗣 Description ##
Fixes Minio Docker deployment issues locally and redirects s3 Client requests to local minio replica s3 instance.

## 💭 Motivation and context ##
Allows for local testing with s3 and adds the ability to not have to hit the actual s3 buckets which require some permission changes for individual AWS IAM roles. 

## 🧪 Testing ##

- Make sure the local .env file has these parameters set exactly as shown (Replace if the values are already set):

>         AWS_ACCESS_KEY_ID=aws_access_key
>         AWS_SECRET_ACCESS_KEY=aws_secret_key
>         EMAIL_BUCKET_NAME=crossfeed-local-exports

- Rebuild the project or run ./rebuild.sh in the root of the project.
- Make sure that minio docker container is running
- Navigate to http://localhost:9000/minio/login
- Login with values:
>         AWS_ACCESS_KEY_ID=aws_access_key
>         AWS_SECRET_ACCESS_KEY=aws_secret_key
- Upload any documents needed to access in s3 (**MAKE SURE FILENAMES MATCH WHAT WILL BE ADDED TO DMZ/PROD S3 VALUES**)

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by schmelz21 — APPROVED** [review]

**Comment by schmelz21** [comment]
@nickviola - you have this in draft.. Should this be active?

**Review by ameliav — APPROVED** [review]
LGTM

**Comment by nickviola** [comment]
https://github.com/cisagov/XFD/pull/355 adds checks for local static banner text. This should be merged first if we decide to go with this minio PR.

**Comment by aloftus23** [comment]
> #355 adds checks for local static banner text. This should be merged first if we decide to go with this minio PR.

reverted what I just did I didn't see that PR 🤦‍♂️

**Pull request merged**
