### PR TITLE
Revert "Merge pull request #237 from cisagov/172-design-vs-graphs"

### PR DESCRIPTION
**Pull request by aloftus23**
This reverts commit a8fc488e3fefbafb71e9c0447c30fe4d3e976c03, reversing changes made to e8fe06d2e01212efa876027b67625bfaf5c29222.

#  #

## 🗣 Description ##

Revert changes in PR linked to #172 

The branch was recreated named 172-design-vs-graphs.

## 💭 Motivation and context ##

Staging-cd started breaking once merged

Was working locally. Theory: there was an overload of data that caused the calls to take too long and went over the 29s limit for API gateway.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Revert dependencies to default branches.
- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Review by Matthew-Grayson — APPROVED** [review]
Looks good.

**Review by rapidray12 — APPROVED** [review]
For a revert it looks good.  Reverted lines of code match the original pull

**Comment by rapidray12** [comment]
[*]

**Review by cduhn17 — APPROVED** [review]
LGTM

**Pull request merged**
