### PR TITLE
Fix Error Message Displayed on the Manage Organizations Page (Global View role)

### PR DESCRIPTION
**Pull request by chrtorres**
#  #

## 🗣 Description ##

- Fixed organizations not displayed on "Manage Organizations" as Global View.

## 💭 Motivation and context ##
Currently, there are no organizations displayed on the Manage Organizations page under the global view role. Under global view, you are able to view organizations but not modify. With this fix, it restores that functionality to a user under global view.

This resolves CRASM - [326](https://maestro.dhs.gov/jira/browse/CRASM-326)

## 📷 Screenshots (if appropriate) ##

Screenshot 2024-08-01 at 1 26 46 PM

Screenshot 2024-08-01 at 1 27 34 PM

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by schmelz21 — APPROVED** [review]

**Review by Matthew-Grayson — APPROVED** [review]
🚀

**Review by Matthew-Grayson — CHANGES_REQUESTED** [review]
Looks and works great. Line 862  (const id =...) seems unnecessary though.

**Comment by chrtorres** [comment]
> Looks and works great. Line 862 (const id =...) seems unnecessary though.

Good catch! The line in question has been removed.

**Review by Matthew-Grayson — APPROVED** [review]
Looks great!

**Pull request merged**
