### PR TITLE
Updates Terms of Use

### PR DESCRIPTION
**Pull request by jayjaybunce**
#  #

## 🗣 Description ##
- Updated the Terms of Use to be displayed (the content has not changed, just the presentation)
    - Boldened the lines about administrative accounts

## 💭 Motivation and context ##

Resolves [CRASM-621](https://maestro.dhs.gov/jira/secure/RapidBoard.jspa?rapidView=23595&projectKey=CRASM&view=planning&selectedIssue=CRASM-621&epics=visible&issueLimit=100)

## 🧪 Testing ##

- Edit the row for your user to null out fields `dateAcceptedTerms` and `acceptedTermsVersion`
- Login to the app
- You should see the updated terms, which should match the terms posted in ticket AC
https://maestro.dhs.gov/jira/browse/CRASM-621

## 📷 Screenshots (if appropriate) ##
Screenshot 2024-09-04 at 11 25 31 AM

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by nickviola — APPROVED** [review]
LGTM

**Comment by schmelz21** [comment]
@jayjaybunce  - we are putting this on hold, as the text may needed edited and reapproved.

**Review by cduhn17 — APPROVED** [review]
LGTM - simple changes

**Review by hawkishpolicy — APPROVED** [review]
LGTM.

**Comment by schmelz21** [comment]
OBE due to text updated merged in https://github.com/cisagov/XFD/pull/648

**Pull request closed without merging**
