### PR TITLE
Refactored VulnerabilityBarChart to show severity level in the order of criticality (CRASM-783)

### LINKED ISSUE #689: Severity Levels bar graph X axis CRASM-783
# 🐛 Summary #

The severity bar graph level of severity X-axis is not in the order of criticality

- Critical
- Null
- Low
- Medium
- High

## Expected behavior ##

Graph should show severity levels from null to critical. 

- Null
- Low
- Medium
- High
- Critical

## Any helpful log output or screenshots ##

Image

### PR DESCRIPTION
**Pull request by lwersiy**
## 🗣 Description ##

This PR does the following:

- null severity values are now placed in the N/A category.
- all severity values are converted to Title Case.
- any value that falls outside of N/A, Low, Medium, High, or Critical is placed in the Other category.
- it rearranges the Severity Level Bar graph X-axis in the correct order from N/A to Other.
- The Other category will serve as an indicator on the front end that data validation in the backend is failing.

## 💭 Motivation and context ##

Closes (CRASM-783) https://maestro.dhs.gov/jira/browse/CRASM-783
Resolves #689 

## 🧪 Testing ##
Tested Locally
- There are no existing values for null and critical locally, so i manually inserted some values to get the resulting bar graph below.

Screenshot 2024-10-15 at 3 10 10 PM

Screenshot 2024-10-22 at 1 17 19 PM

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ x These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by jayjaybunce — APPROVED** [review]
Tested locally, looks good.

**Review by chrtorres — APPROVED** [review]
LGTM per Code review 10/18/24

**Review by schmelz21 — CHANGES_REQUESTED** [review]
Can we change the value of "null" to display as "N/A" as it is seen in the Inventory/Vulnerabilities page. 
Screenshot 2024-10-22 at 12 22 52 PM

**Review by jayjaybunce — APPROVED** [review]
LGTM

**Review by nickviola — APPROVED** [review]
LGTM

**Review by schmelz21 — APPROVED** [review]

**Pull request merged**
