### PR TITLE
Changed User Registration "Region Admin" from "h4" to "h1"(CRASM-378) 

### LINKED ISSUE #386: UI: (10.B) User Registration "Region Admin" tagged as <h4> (CRASM-378)
# 🐛 Summary #

“Region 3 Admin Dashboard” is tagged as "h4" level heading. Since this text is the main heading on the page, it should be coded as "h1" level heading. The subsequent headings on the page “Pending Requests” and “Members of Region 3” should be tagged as "h2" level headings.

## Any helpful log output or screenshots ##

image

### PR DESCRIPTION
**Pull request by lwersiy**
## 🗣 Description ##

User Registration "Region Admin Dashboard" was modified from "h4" to "h1"
Pending Requests modified to "h2"
Members of Region 3 modified to "h2"

## 💭 Motivation and context ##
closes #421
closes CRASM 378

## 🧪 Testing ##

tested on crossfeed local

## 📷 Screenshots (if appropriate) ##
Screenshot 2024-07-10 at 12 49 19 PM
Screenshot 2024-07-10 at 12 49 45 PM
Screenshot 2024-07-10 at 12 49 58 PM

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by hawkishpolicy — CHANGES_REQUESTED** [review]
The H1 and H2 tags need to be styled accordingly. The default font size is too large.

**Review by ameliav — CHANGES_REQUESTED** [review]
Please change the font size. This PR can be used as an example: https://github.com/cisagov/XFD/pull/413

**Review by ameliav — APPROVED** [review]
LGTM!

**Review by schmelz21 — APPROVED** [review]
Good update.. nice review.

**Review by hawkishpolicy — APPROVED** [review]
LGTM.

**Pull request merged**
