### PR TITLE
Organization/Regional filter rollup - Minor fixes and enhancements

### PR DESCRIPTION
**Pull request by jayjaybunce**
#  #

## 🗣 Description ##

- Updates FilterTags to ensure padding when there are two rows of tags
- Updated FilterTags to truncate what text is shown 
- Updated region filters to display as sorted in ascending order
- Resolves request to allow user to click a bar within most-common ports and be taken to a pre-filtered view in inventory
- Updated organization search dropdown options to provide feedback to the user upon selection
- Updated organization search input to clear on user click as well as pressing "Enter" when using keyboard to navigate options.

## 💭 Motivation and context ##

Per Amelia's review on the work in staging: [Teams review breakdown](https://teams.microsoft.com/l/message/19:df930a148b5a4db6b73711196951fa6d@thread.v2/1724359244052?context=%7B%22contextType%22%3A%22chat%22%7D)

## 📷 Screenshots (if appropriate) ##
Screenshot 2024-08-25 at 10 32 30 PM

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Comment by hawkishpolicy** [comment]
Looks like there might be a couple unused imports in Org Search.

src/components/OrganizationSearch.tsx
  Line 22:3:  'AccountCircle' is defined but never used  @typescript-eslint/no-unused-vars
  Line 25:3:  'PersonOutline' is defined but never used  @typescript-eslint/no-unused-vars

**Review by hawkishpolicy — CHANGES_REQUESTED** [review]
Remove unused imports in Org Search.

**Review by ameliav — CHANGES_REQUESTED** [review]
Overall it looks good and is working for me.

image

One thing, can you have the "Search Organizations" emptied after a selection is made? Aka on click or enter. (For example from the screenshot, since "Pensive Department" has already been selected, the box can be empty.)

**Comment by jayjaybunce** [comment]
> Overall it looks good and is working for me.
> 
> image
> 
> One thing, can you have the "Search Organizations" emptied after a selection is made? Aka on click or enter. (For example from the screenshot, since "Pensive Department" has already been selected, the box can be empty.)

I initially spent time working on this issue but ran into some struggles, I can update the component to clear the search when you select a value (click the option you want) but allowing the user to select one with the enter key is more complex with how MUI's Autocomplete api is restrictive.

**Review by ameliav — APPROVED** [review]
LGTM!
- [x] Updates FilterTags to ensure padding when there are two rows of tags
- [x] Updated FilterTags to truncate what text is shown
- [x] Updated region filters to display as sorted in ascending order
- [x] Resolves request to allow user to click a bar within most-common ports and be taken to a pre-filtered view in inventory (CRASM-533)
- [x] Updated organization search dropdown options to provide feedback to the user upon selection
- [x] Updated organization search input to clear on user click as well as pressing "Enter" when using keyboard to navigate options.

**Review by schmelz21 — APPROVED** [review]

**Review by hawkishpolicy — APPROVED** [review]

**Pull request merged**
