### PR TITLE
Update User Registration with update Org functionality for pending users

### PR DESCRIPTION
**Pull request by ameliav**
#  #

## 🗣 Description ##
Update User Registration with update Org functionality for pending users.

## 💭 Motivation and context ##
Pending users have the ability to get an org assigned before becoming a member which requires additional functionality in the User Registration Process.
CRASM-657

## 🧪 Testing ##
Registering a user after they already have an organization assigned to them is now possible.
- If the pending user's org was already added and not modified, only update the user, not org.
- If the pending user now has a different org than before, remove the previous org, then add the new org, and then update the user.
- If the pending user had no previous org, add the user to the selected org which then also updates the user.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by schmelz21 — COMMENTED** [review]
The functionality works perfectly, only if when the Regional Admin selects the same organization that was set in the pending state. It fails if the organization is changed to a different org. If this is acceptable with stakeholders I can move forward to approve. Confirming with stakeholders.

**Comment by ameliav** [comment]
> The functionality works perfectly, only if when the Regional Admin selects the same organization that was set in the pending state. It fails if the organization is changed to a different org. If this is acceptable with stakeholders I can move forward to approve. Confirming with stakeholders.

Hey @schmelz21 can you try again? I had plugged in the wrong org ID for that scenario. It should be working now.

**Review by hawkishpolicy — APPROVED** [review]
Tested local and confirmed with DBeaver.

**Review by nickviola — APPROVED** [review]
LGTM

**Review by schmelz21 — APPROVED** [review]
LGTM

**Pull request merged**
