### PR TITLE
Change email references to Crossfeed to CyHy Dashboard

### PR DESCRIPTION
**Pull request by JCantu248**
#  #

## 🗣 Description ##

Email subject lines and body messages that reference Crossfeed should be updated to CyHy Dashboard

## 💭 Motivation and context ##

This needs to be changed in order to update to the new name of the service.

## 🧪 Testing ##

Code is tested in AWS. 

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Revert dependencies to default branches.
- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Review by cduhn17 — APPROVED** [review]
LGTM

**Review by chrtorres — APPROVED** [review]
LGTM

**Review by rapidray12 — APPROVED** [review]
Simple enough. Crossfeed -> CyHY

**Review by DJensen94 — APPROVED** [review]
LGTM, very elegant code changes

**Pull request merged**
