### PR TITLE
Update the Organization Details tab with additional and working fields

### PR DESCRIPTION
**Pull request by ameliav**
#  #

## 🗣 Description ##
Update the Organization Details tab with additional and working fields

## 💭 Motivation and context ##
In "Manage Organizations", when you click on a specific organization View/Edit, it will go to the "Settings" tab for that organization. The buttons and popups are using legacy code. Also the adding of tags functionality is broken. Also the organization's region and state was not being displayed before.
CRASM-665

## 🧪 Testing ##

- Region and state will now display if the organization has those details.
- Save button is disabled until a change is made to any of the fields.
- Adding/updating tags now works.

## 📷 Screenshots ##
Previous
image
image
image

Updated
image
image
image

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by hawkishpolicy — CHANGES_REQUESTED** [review]
Per our conversation:
- The title for the Tags modal = 'Update Tags".
- The Tags modal save button = "Update".
- The grayed out text providing user instruction =

image

**Comment by ameliav** [comment]
> Per our conversation:
> 
> * The title for the Tags modal = 'Update Tags".
> * The Tags modal save button = "Update".
> * The grayed out text providing user instruction =
> 
> image

Good idea :) Should give users clear instructions on how to interact with the UI. [b99558e](https://github.com/cisagov/XFD/pull/609/commits/b99558eafc6538519a3dea45e9a9078db3311910)

image

**Review by cduhn17 — APPROVED** [review]
LGTM- reviewed in group

**Review by schmelz21 — APPROVED** [review]

**Review by chrtorres — APPROVED** [review]
LGTM per code review

**Review by hawkishpolicy — APPROVED** [review]

**Pull request merged**
