### PR TITLE
Remove ReadySetCyber (RSC) from TypeScript Backend.

### LINKED ISSUE #717: Remove ReadySetCyber Backend Code (CRASM-810/811/813)
# 💡 Summary #

Remove RSC endpoints and models.
Remove RSC user type.
Remove rscSync scan.

Purge ReadySetCyber users from database

### PR DESCRIPTION
**Pull request by Matthew-Grayson**
Delete TypeORM models for Assessment, Category, Question, Resource, and Response Delete RSC API endpoints
Delete rscSync scan
Delete RSC-related imports in connection.ts, index.ts, and worker.ts Delete mission instance credentials in dev.env.example

#  #

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by chrtorres — APPROVED** [review]
LGTM per code review on 11/14/24

**Review by aloftus23 — APPROVED** [review]
Looks good to me

**Review by nickviola — APPROVED** [review]
LGTM

**Review by hawkishpolicy — APPROVED** [review]
LGTM.

**Review by jayjaybunce — APPROVED** [review]
Tested functionality across the app and didn't find any impacted functionality.

**Pull request merged**
