### PR TITLE
Added Severity Label validation to All Vulns table (CRASM-822)

### PR DESCRIPTION
**Pull request by hawkishpolicy**
- Extends severity level validation used in VulnerabilityBarChart.tsx to the All Vulnerabilities table.
- This ensures continuity of Severity labels between the bar graph and table.
- Also ensures that server side based filtering returns accurate results.

#  #

## 🗣 Description ##
- Ensured that null or empty string values are displayed as 'N/A' in the severity column of the All Vulns table.
- Ensured that values of Other or any value that does not include 'Critical', 'High', 'Medium', or 'Low' are displayed as 'Other' in the severity column of the All Vulns table..
- Formatted the severity column of the All Vulns table to display the severity label in title case.
- Updated the vulnerability search endpoint to return vulnerabilities with a severity of 'Other' if the severity is not 'Critical', 'High', 'Medium', or 'Low'.
- Updated the vulnerability search endpoint to return vulnerabilities with a severity of 'N/A' if the severity is null or an empty string.
- Updated the vulnerability search endpoint to return vulnerabilities regardless of the case of the severity value.

## 💭 Motivation and context ##
- Closes CRASM-822

## 🧪 Testing ##
- Seeded local database with numerous vulnerabilities containing irregular severity labels.
- Filtered via table and bar graph to see if accurate results were returned. 

## 📷 Screenshots (if appropriate) ##
Screenshot 2024-11-08 at 12 12 41 PM
Screenshot 2024-11-08 at 12 11 58 PM
Screenshot 2024-11-08 at 12 12 48 PM
Screenshot 2024-11-08 at 12 10 58 PM
Screenshot 2024-11-08 at 1 50 27 PM
Screenshot 2024-11-08 at 1 50 22 PM

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by lwersiy — APPROVED** [review]
Looks good

**Review by jayjaybunce — APPROVED** [review]
Found two small bugs, resolved these together with @hawkishpolicy 

LGTM after checks pass

**Review by chrtorres — APPROVED** [review]
LGTM

**Review by schmelz21 — APPROVED** [review]
LGTM

**Pull request merged**
