### PR TITLE
Remove default values to trigger state selection

### PR DESCRIPTION
**Pull request by nickviola**
Resolves CRASM-558 Allows state selection on new user creation if one does not exist.

#  #

## 🗣 Description ##
Removes default state values to prompt the state selection screen on login if a user doesn't have the value populated.

## 💭 Motivation and context ##
CRASM-558

## 🧪 Testing ##
Register for a new user in login.gov or remove existing users state/region value and you should be prompted with the screenshot on login if the state/region values are missing. After state is selected, the region will automatically be set as well in the database.

Screenshot 2024-09-04 at 10 44 43 AM

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by Matthew-Grayson** [comment]
GitHub Actions failed on Backend Pipeline / build_worker. It looks like a fluke so I'm re-running the check.

**Review by schmelz21 — APPROVED** [review]
LGTM - Tested locally the functionality and re-ran build worker successfully. 
@Matthew-Grayson - did you want to re-review?

**Review by hawkishpolicy — APPROVED** [review]
Looks good to me.

**Review by cduhn17 — APPROVED** [review]
LGTM

**Pull request merged**
